dist: xenial
language: python
python: 3.7
cache:
  pip: true
script:
  - echo 'Nothing to do'
deploy:
  provider: heroku
  api_key:
    secure: oVnOxZR8giBINnSCwrMhTTnpBaDZM1iuGKpb4XRMkGhZWUAoR18xqiQ2pekkQiDUwVFw5DUsUvTO2sCuamwyJY9HtG99M4xEjJrfW0gfx4ojHXBq/yna3RH1J1STN5vH1/fethQfdiPVB/v/Op81RGe0LYbHdyVSZdFe6RHpZH56iAeQHBsxpjqQ5M130rEahykGpqNzlifKSlSSzI1H0y8jrbQvZ6GnxHwotSUcXQa4+VTcnaIzYQ+ea7BOO0V/7RdE3gTTGPRuQzGHEEaBmRadCVhoUhZH0R+cRLPX3PTgojluQ55joFqKMMM13k72kkqIe9nHrGT/ZYJbek5p2bUkROVbBWfc8s95pths1BZJ1FsPZJ9tY9iTyx8YTg+8qDzZdJ0bdwriyCb7V82Hc9XF3w7kLuaUix7lC9/H17mxKn9JBreM6pfX2diEvQWPzhTbHOD+5WJuJLR+hs39JZiLcqlvb6tjYoGU974J9uftFvwaW5zChvFFdazdDnBhtaDyR8bcCT8TmocdlsYNCwNxokSj9DXgD7WbjwXvbxrs1TmhQSYCm1wkT45yxL4HXy4W+pJdcvRNjjdayboo/fPcbaFtbWmkx+iUS1IFDWGUg7gZx5G9Ys8wCRWYhVqmetAsP35yqOolACQig2rcJuSRFEPzn4sIM+2tW36Q+m8=
  on: master
